name: Compile Typst
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Typst
        uses: charlyhs/setup-typst@v3
        with:
          version: 0.14.2

      - name: Compile PDF
        run: typst compile main.typ main.pdf

      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled-pdf
          path: main.pdf
